# Preparation

In [1]:
import math
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from trafficSimulator import *

def parallel_line(current_coordinates, distance):
    x1, y1 = current_coordinates[0]
    x2, y2 = current_coordinates[1]
    k = (y1-y2)/(x1-x2)
    b = y1 - k*x1
    
    cross_x = -b/k
    hypo = math.sqrt(b**2+cross_x**2)
    
    if k>0:
        new_coord_1 = ((x2+distance*abs(b)/hypo, y2-distance*abs(cross_x)/hypo),
                       (x1+distance*abs(b)/hypo, y1-distance*abs(cross_x)/hypo))

        new_coord_2 = ((x2-distance*abs(b)/hypo, y2+distance*abs(cross_x)/hypo),
                       (x1-distance*abs(b)/hypo, y1+distance*abs(cross_x)/hypo))
        
    else:
        new_coord_1 = ((x2+distance*abs(b)/hypo, y2+distance*abs(cross_x)/hypo),
                       (x1+distance*abs(b)/hypo, y1+distance*abs(cross_x)/hypo))
    
        new_coord_2 = ((x2-distance*abs(b)/hypo, y2-distance*abs(cross_x)/hypo),
                       (x1-distance*abs(b)/hypo, y1-distance*abs(cross_x)/hypo))
    
    return new_coord_1, new_coord_2

pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html

# Simulation setup

In [2]:
left, right = -100*math.sqrt(3), 100*math.sqrt(3)
bottom, top = -100, 100

vehicle_rate = 45
v_max = 10
s0 = 5
T = 1.5
b_max = 3
a_max = 2

fast_track_factor, slow_track_factor = 1, 0.8
stop_distance = 50
wait_time = 2
vehicle_limit = 20

record_df = pd.DataFrame(columns=['Vehicle_label', 'Road_order', 
                                  'Total_time', 'Leading_vehicles',
                                  'Stopped_time', 'Stop_while_front'])

left_bottom_outbound = ((left+2, 4), (-5, top-2),
                        slow_track_factor, stop_distance, wait_time)
bottom_right_outbound = ((5, top-2), (right-2, 4),
                         fast_track_factor, stop_distance, wait_time)

left_top_outbound = ((left+2, -4), (-5, bottom+2),
                     fast_track_factor, stop_distance, wait_time)
top_right_outbound = ((5, bottom+2), (right-2, -4),
                      slow_track_factor, stop_distance, wait_time)

bottom_left_inbound = parallel_line(current_coordinates=left_bottom_outbound, 
                                    distance=2.5)[0]
right_bottom_inbound = parallel_line(current_coordinates=bottom_right_outbound, 
                                     distance=2.5)[1]

top_left_inbound = parallel_line(current_coordinates=left_top_outbound, 
                                 distance=2.5)[0]
right_top_inbound = parallel_line(current_coordinates=top_right_outbound, 
                                  distance=2.5)[1]

## For the connections of the topology, we can either represent with concrete lines
## or just as a dot (as shown below). Either case, the vehicles will not actually go 
## pass these routes; they are more for demonstration purposes

connection_top_bottom = ((-1.25, bottom+2), (-1.25, top-2))
connection_bottom_top = ((1.25, top-2), (1.25, bottom+2))

# Or just show a dot:

# connection_top_bottom = ((-1.25, -2), (-1.25, 2))
# connection_bottom_top = ((1.25, 2), (1.25, -2))

# Create and run simulation

In [3]:
 def run_simulation(all_routes, vehicle_limit, records, vehicle_preferences,
                   vehicle_rate, vehicle_specs):
    global left_bottom_outbound
    global bottom_right_outbound
    global left_top_outbound
    global top_right_outbound
    global connection_top_bottom
    global connection_bottom_top
    global bottom_left_inbound
    global right_bottom_inbound
    global top_left_inbound
    global right_top_inbound
    
    sim = Simulation({
        'all_routes': all_routes, # All possible (and reasonable) routes
        'vehicle_limit': vehicle_limit, # Total number of vehicles in simulation
        'records': records, # Table that will capture the needed vehicle-related info
        'vehicle_preferences': vehicle_preferences
        # A dictionary that stores the vehicles' labels are keys and their list of probabilities
        # of choosing each possible route as values
        # For the initial few rounds all vehicles choose all routes with equal weights.
        # For more complicated topologies some other algorithms will be needed as all possible
        # routes are not as explicit as in here.
        })

    sim.create_roads([
        ## Key routes
        left_bottom_outbound, # Road #0
        bottom_right_outbound, # Road #1

        left_top_outbound, # Road #2
        top_right_outbound, # Road #3

        connection_top_bottom, # Road #4
        connection_bottom_top, # Road #5

        bottom_left_inbound, # Road #6
        right_bottom_inbound, # Road #7

        top_left_inbound, # Road #8
        right_top_inbound, # Road #9

        ## Curved corners
        # Note: in the simulation, the vehicles will not actually go pass these
        # routes; they are more for aesthetic purposes

        # Outbound corners
        *curve_road(left_bottom_outbound[1], 
                    (bottom_right_outbound[0][0], bottom_right_outbound[0][1]+0.01), 
                    (0, top), 16), # Outbound bottom corner; Roads #10-#25

        *curve_road(left_top_outbound[1], 
                    (top_right_outbound[0][0], top_right_outbound[0][1]+0.01), 
                    (0, bottom), 16), # Outbound top corner; Roads #26-#41

        *curve_road(left_bottom_outbound[0], 
                    (left_top_outbound[0][0]+0.01, left_top_outbound[0][1]), 
                    (left, 0), 16), # Outbound left corner; Roads #42-#57

        *curve_road(bottom_right_outbound[1], 
                    (top_right_outbound[1][0]+0.01, top_right_outbound[1][1]), 
                    (right, 0), 16), # Outbound right corner; Roads #58-#73

        # Inbound corners
        *curve_road(right_bottom_inbound[1], 
                    (bottom_left_inbound[0][0], bottom_left_inbound[0][1]+0.01), 
                    (0, top), 16), # Inbound bottom corner; Roads #74-#89

        *curve_road(right_top_inbound[1], 
                    (top_left_inbound[0][0], top_left_inbound[0][1]+0.01), 
                    (0, bottom), 16), # Inbound top corner; Roads #90-#105

        *curve_road(bottom_left_inbound[1], 
                    (top_left_inbound[1][0]+0.01, top_left_inbound[1][1]), 
                    (left+2.5, 0), 16), # Inbound left corner; Roads #106-#121

        *curve_road(right_bottom_inbound[0], 
                    (right_top_inbound[0][0]+0.01, right_top_inbound[0][1]), 
                    (right-2.5, 0), 16), # Inbound right corner; Roads #122-#137
    ])


    sim.create_gen({
        'vehicle_rate': vehicle_rate, # Rate of generating new vehicles
        'vehicle_limit': vehicle_limit, # Total number of vehicles in simulation
        'vehicles': vehicle_specs
        })


    # Start simulation
    win = Window(sim)
    win.zoom = 3
    new_records = win.run(steps_per_update=5)
    
    return new_records

In [4]:
all_routes = [[0, 3], [0, 1], [2, 3], [2, 1]]
vehicle_specs = {'v_max': v_max, # Desired speed
                 's0': s0, # Safe bumper-to-bumper distance
                 'T': T, # Time gap
                 'b_max': b_max, # Deceleartion
                 'a_max': a_max, # Acceleration
                }

In [5]:
vehicle_preferences = dict(zip(range(vehicle_limit), 
                               [[0.25, 0.25, 0.25, 0.25]]*vehicle_limit))

record_df = run_simulation(all_routes, vehicle_limit, record_df, vehicle_preferences,
                             vehicle_rate, vehicle_specs)

In [6]:
record_df

,Vehicle_label,Road_order,Total_time,Leading_vehicles,Stopped_time,Stop_while_front
0,7,"[0, 3]",43.5,"[-999, -999]","[0, 0]","[0, 0]"
1,14,"[2, 3]",48.18,"[-999, 7]","[0, 0]","[0, 0]"
2,18,"[0, 1]",39.64,"[7, -999]","[0, 0]","[0, 0]"
3,12,"[2, 3]",51.58,"[14, 14]","[0, 0]","[0, 0]"
4,1,"[2, 3]",62.38,"[12, 13]","[2.2000000000000015, 0]","[2.2000000000000015, 0]"
5,5,"[2, 3]",72.5,"[1, 4]","[0.5600000000000002, 0.19999999999999998]","[0.5600000000000002, 0]"
6,13,"[0, 3]",52.42,"[18, 12]","[0.7400000000000003, 0.5200000000000001]","[0.7400000000000003, 0]"
7,2,"[2, 1]",71.24,"[5, 16]","[0.34, 0.6400000000000002]","[0.34, 0]"
8,9,"[0, 1]",47.58,"[13, 18]","[0, 0]","[0, 0]"
9,17,"[2, 1]",78.92,"[2, 15]","[0.19999999999999998, 0.5800000000000002]","[0.19999999999999998, 0]"
10,10,"[0, 1]",51.42,"[9, 9]","[0, 0]","[0, 0]"
11,4,"[0, 3]",59.52,"[10, 1]","[0, 0]","[0, 0]"
12,16,"[0, 1]",59.74,"[4, 10]","[0, 0]","[0, 0]"
13,0,"[2, 3]",80.22,"[17, 5]","[0, 0]","[0, 0]"
14,15,"[0, 1]",67.7,"[16, 2]","[0, 0]","[0, 0]"
15,6,"[2, 3]",84.5,"[0, 0]","[0, 0]","[0, 0]"
16,11,"[2, 3]",89.4,"[6, 6]","[0, 0]","[0, 0]"
17,19,"[0, 1]",75.6,"[15, 17]","[0, 0]","[0, 0]"
18,8,"[2, 1]",89.18,"[11, 3]","[0, 0]","[0, 0]"
19,3,"[0, 1]",81.72,"[19, 19]","[0, 0]","[0, 0]"

In [7]:
gamma_mean, gamma_var = 1, 0.5
eta_mean, eta_var = 1, 0.5
# np.random.normal(gamma_mean, gamma_var, 10)

In [8]:
utility_df = record_df[['Vehicle_label', 'Road_order', 'Total_time']]

utility_df['Gamma'] = np.random.normal(gamma_mean, gamma_var, len(utility_df))
utility_df['Eta'] = np.random.normal(eta_mean, eta_var, len(utility_df))
utility_df['Caused_delay'] = 0.0

utility_df = utility_df.sort_values('Vehicle_label', ascending=True).reset_index(drop=True)


for idx, row in record_df.iterrows():
    current_l = row['Vehicle_label']
    stop_times = row['Stopped_time']
    lead_v = row['Leading_vehicles']
    
    for i in range(len(stop_times)):
        if stop_times[i] > 0:
            utility_df.at[lead_v[i], 'Caused_delay'] += stop_times[i]
            
utility_df

   Vehicle_label Road_order Total_time     Gamma       Eta  Caused_delay
0              0     [2, 3]      80.22  1.650093  0.427846          0.00
1              1     [2, 3]      62.38  0.999863  1.162169          0.56
2              2     [2, 1]      71.24  0.634959  0.389810          0.20
3              3     [0, 1]      81.72  0.735489  1.230298          0.00
4              4     [0, 3]      59.52  1.670225  0.984591          0.20
5              5     [2, 3]       72.5  1.530926  1.974241          0.34
6              6     [2, 3]       84.5  1.276265  1.147122          0.00
7              7     [0, 3]       43.5  0.825296  1.560458          0.00
8              8     [2, 1]      89.18  1.225159  0.269968          0.00
9              9     [0, 1]      47.58  1.543559  1.241192          0.00
10            10     [0, 1]      51.42  0.761327  1.070182          0.00
11            11     [2, 3]       89.4  1.068795  0.522620          0.00
12            12     [2, 3]      51.58  1.125146  1.526940          2.72
13            13     [0, 3]      52.42  1.235467  0.229925          0.00
14            14     [2, 3]      48.18  0.028500  0.716073          0.00
15            15     [0, 1]       67.7  1.441451  0.943930          0.58
16            16     [0, 1]      59.74  0.554570  1.884815          0.64
17            17     [2, 1]      78.92  0.152370  0.980480          0.00
18            18     [0, 1]      39.64  0.823767  1.388640          0.74
19            19     [0, 1]       75.6  1.551729  0.970309          0.00